name: Deploy to gh-pages

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - run: npm deploy
